version: '3.3'

services:
  backend:
    build:
      context: ./sql-be
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    networks:
      - my_network
    
 
  frontend:
    build:
      context: ./sql-fe
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - my_network

  # nginx:
  #   image: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - backend
  #     - frontend
  #   networks:
  #     - my_network
        
networks:
  my_network:
    driver: bridge